### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by wait1212** [sgraine/point-label-aware-superpixels#6]
where is dataset.can't find it.Link has expired

**Comment by Tobias-Fischer** [comment]
Which dataset, and which link?

**Comment by wait1212** [comment]
this link:
https://sites.google.com/a/unizar.es/semanticseg/home&nbsp;
the dataset is UCSD Mosaic dataset
thank you!
please!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tobias ***@***.***&gt;; 
发送时间: 2023年6月24日(星期六) 下午4:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sgraine/point-label-aware-superpixels] dataset (Issue #6)





 
Which dataset, and which link?

**Comment by Tobias-Fischer** [comment]
Please contact the authors of https://sites.google.com/a/unizar.es/semanticseg/home/ as we do not have the permission to redistribute their data.
